# Generated by Django 5.1.3 on 2024-11-08 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='order_receivers',
            field=models.ManyToManyField(blank=True, related_name='received_order_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
